spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yomic-drive?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true

    open-in-view: true
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
app:
  path: /Users/zhangyin/IdeaProjects/yomic-drive/files

